# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "787d83dca600474d64ea044ad28e4a2d"
name = "containerdoo-calculator"
application_url = "https://containerdoor-nz-freight-calculator.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_shipping,read_shipping,read_orders"

[auth]
redirect_urls = [ "https://containerdoor-nz-freight-calculator.vercel.app/api/auth" ]
